spring:
  ##thymeleaf静态资源配置  
  thymeleaf:
    ##模版模式
    mode: HTML5
    ##编码
    encoding: UTF-8
    servlet:
      content-type: text/html
    ##关闭模版缓存，即时刷新
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    name: mytest
    #基本属性 url user password
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf-8&autoReconnect=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    ##配置MVC静态资源映射
    static-path-pattern: /**

mybatis:
  #mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #检查配置文件是否存在
  check-config-location: true
  #定义别名所在包
  type-aliases-package: com.springboot.entity

#showSQL
logging:
  level:
    com.springboot.dao: debug